# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 677)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 641, 621))
        self.textBrowser.setObjectName("textBrowser")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-size:14pt; font-weight:600; background-color:#ffffff;\">Жизнь</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; background-color:#ffffff;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111;\">Игра Жизнь- это клеточный автомат созданный в 1970 году Джоном Конвеем</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">Это не совсем игра, а просто симуляция клеток по определенным правилам.От игрока лишь требуется размещать эти клетки.</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Fira Sans,sans-serif\'; font-size:14pt; font-weight:496; color:#111111; background-color:#ffffff;\">Правила</span></p>\n"
                                            "<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">Клетка - она может быть либо живой (темной), либо мертвой (белой).</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">У клетки есть 8 соседей вокруг и могут влиять на нее.</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">Если клетка мертва и у нее есть 3 живых соседа, тогда она рождается.</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">Если клетка жива и у нее есть 2 или 3 соседа, то она остается живой.В противном случае умирает от перенаселения или одиночества</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; font-weight:600; color:#111111; background-color:#ffffff;\">Управление</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">LMB - оживить клетку</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">RMB - убить клетку</span></p>\n"
                                            "<p style=\" margin-top:24px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Arial,sans-serif\'; font-size:14pt; color:#111111; background-color:#ffffff;\">Space - остановка времени</span></p></body></html>"))
        self.back_btn.setText(_translate("Form", "<- Назад"))
